---
title: "Create merged data set"
output:
  pdf_document: default
date: "2023-08-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(foreign)
library(labelled) 
library("dplyr")
library(here)
```

# Read in data
Data downloaded from https://www.pewresearch.org/american-trends-panel-datasets/. 
Waves 64, 66, 83, 114 have mental health data used to construct psychological distress score. Wave 66 is not used in the final analysis. 
Wave 64 also has self or household income or job loss. 
Wave 72 has self or household income or job loss. 
Wave 54 has prepandemic finances.

```{r read_data}
rm(list=ls())
#data_path <- file.path("/Users","graceringlein","OneDrive - Johns Hopkins","PewMH","data","rawdata")

#READ IN DATA FOR MENTAL HEALTH WAVES
W114 <- read_sav(here("data","ATP W114.sav"))
W64 <- read_sav(here("data","ATP W64.sav"))
#W66 <- read_sav(here("data","ATP W66.sav"))
W83 <- read_sav(here("data","ATP W83.sav"))

#READ IN WAVES WITH FINANCIAL COVARIATES
W54 <- read_sav(here("data","ATP W54.sav"))
#W65 <- read_sav(here("data","ATP W65.sav"))
W72 <- read_sav(here("data","ATP W72.sav"))

```


```{r} 
#RENAME COLUMNS THAT DON'T HAVE WAVE NUM
W54 <- W54 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W54'))
W64 <- W64 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W64'))
#W65 <- W65 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W65'))
#W66 <- W66 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W66'))
W72 <- W72 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W72'))
W83 <- W83 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W83'))
W114 <- W114 %>% rename_at(vars(!matches("*(_W..)"),-QKEY), ~paste0(., '_W114')) 

#ADD RESPONDED COLUMN
W64$F_RESPONDED_W64 <- c(rep(1,nrow(W64)))
#W66$F_RESPONDED_W66<- c(rep(1,nrow(W66)))
W54$F_RESPONDED_W54 <- c(rep(1,nrow(W54)))
#W65$F_RESPONDED_W65 <- c(rep(1,nrow(W65)))
W72$F_RESPONDED_W72 <- c(rep(1,nrow(W72)))
W83$F_RESPONDED_W83 <- c(rep(1,nrow(W83)))
W114$F_RESPONDED_W114 <- c(rep(1,nrow(W114)))

```


```{r}
#MERGE MH DATA AND REMOVE DUPLICATE COLUMNS
W_MH <- W64 %>% #full_join(W66,by="QKEY",suffix=c("","_dup")) %>%
  full_join(W83,by="QKEY",suffix=c("","_dup")) %>%
  full_join(W114,by="QKEY",suffix=c("","_dup"))

W_MH <- W_MH %>% select(!contains("dup"))

#MERGE COVARIATE DATA
W_cov <- W54 %>% 
  #full_join(W65,by="QKEY",suffix=c("","_dup")) %>%
  full_join(W72, by="QKEY",suffix=c("","_dup")) 

W_cov <- W_cov %>% select(!contains("dup"))

#MERGE MH AND COV
W <- left_join(W_MH,W_cov,by="QKEY",suffix=c("_dup",""))
W <- W %>% select(!contains("dup"))
```

```{r}
# REORDER
W <- W %>% relocate("QKEY",contains("RESPONDED"))
```


```{r}
#SELECT COLUMNS OF INTEREST

W_wide <- W %>% select("QKEY",
                  contains("RESPONDED"),
                  contains("WEIGHT"),
                  
                  #DEMOGRAPHICS
                  contains("GENDER"),contains("SEX"),
                  contains("RACE"),contains("HISP"),
                  contains("CREGION"),
                  contains("METRO"),
                  contains("EDUCCAT"),#contains("EDUC_ACS"),
                  contains("MARITAL"),
                  contains("AGE"),
                  contains("CITIZEN"),
                  contains("LANG"),
                  contains("HH"),
                  contains("PARENT"),
                  
                  #MENTAL HEALTH
                  contains("MH_TRACK"),contains("MHEALTH"),contains("MENTAL"),
                  #contains("SATLIFE"), 
                  
                  #FINANCES
                  contains("INC_TIER2"),
                  contains("INC_SDT"),
                  contains("FIN_SIT"),contains("FINANCE"),contains("DEBT"),contains("BENEFITS"),contains("BILLSTYPICAL"),contains("BILLSNOW"),contains("EMERG"), contains("SAVINGS"),contains("INSURANCE"),contains("OWNRENTMOD"),
                  contains("WORRY2"),contains("PERSFNC"),
                  
                  #COVID EMPLOYMENT
                  contains("E_COVID"),contains("COVID_INDVD"),contains("COVID_AIDPERS"), contains("POSTCOVID"), contains("COVIDCHG"),
                  contains("E3"),contains("E1"),contains("E2"),
                  contains("COVIDWORK"),
                  
                  #INTERNET USE
                  #contains("INTFREQ"),
                  
                  #POLITICAL
                  #contains("PARTY"),
                  
                  #RELIGION
                  #contains("RELIG"),contains("ATTEND"),
                  #contains("RELIMP"),contains("PRAY"),contains("GOD"),contains("HGHPWR"),contains("COVIDSPIR"),contains("CHURCHPOL"), contains("RELIG_INFL"),contains("RELFAV"),contains("ESSENT"),
                  
                  #COMMUNITY
                  #contains("COMTYPE2"),contains("COMATTACH"),
                  #contains("SOCTRUST"), contains("GSSTRUST"),
                  
                  #VOLUNTEERING
                  #contains("VOLSUM"),contains("VOL12"),
                  
                  #SCIENCE
                  #contains("SC1"),contains("CONF"),contains("POLICY"),contains("FAUCI"),contains("COVID_INFECT"), contains("RQ2")
                  )


```

```{r}
# REPLACE 99 WITH NA
W_wide <- W_wide %>% mutate(across(where(is.numeric),~na_if(.x,99)))
```

```{r}
#WEIGHTS FROM PEW AS OF 8/15/2023
W_wide <- tryCatch({
  weights <- read_sav(here("data","ATP_W54-64-72-83-114_weights.sav"))
  W_wide %>% left_join(weights,by="QKEY")
 }, error=function(e){
   message(e)
   return(W_wide)
}) 

W_wide %>% select(contains("WEIGHT"))

```


```{r}
#TO STATA FORMAT
#write.dta(W_wide, file.path("/Users","graceringlein","OneDrive - Johns Hopkins","PewMH","data","pewMH_dataset_merged_090623.dta"))
```


```{r}
# SAVE DATA
write_sav(W_wide, here("data","pewMH_dataset_merged.sav"))
message(paste("Saved combined dataset to"),here("data","pewMH_dataset_merged.sav"))
rm(list=ls())
```
